//
// This file is automatically generated by generate.go -- Do not edit!
//
package main

import (
	_ "github.com/vtolstov/cloudagent/command/guest_agent_update"
	_ "github.com/vtolstov/cloudagent/command/guest_exec"
	_ "github.com/vtolstov/cloudagent/command/guest_exec_status"
	_ "github.com/vtolstov/cloudagent/command/guest_file_chmod"
	_ "github.com/vtolstov/cloudagent/command/guest_file_chown"
	_ "github.com/vtolstov/cloudagent/command/guest_file_close"
	_ "github.com/vtolstov/cloudagent/command/guest_file_flush"
	_ "github.com/vtolstov/cloudagent/command/guest_file_open"
	_ "github.com/vtolstov/cloudagent/command/guest_file_read"
	_ "github.com/vtolstov/cloudagent/command/guest_file_seek"
	_ "github.com/vtolstov/cloudagent/command/guest_file_stat"
	_ "github.com/vtolstov/cloudagent/command/guest_file_write"
	_ "github.com/vtolstov/cloudagent/command/guest_fscheck"
	_ "github.com/vtolstov/cloudagent/command/guest_fsfreeze_freeze"
	_ "github.com/vtolstov/cloudagent/command/guest_fsfreeze_freeze_list"
	_ "github.com/vtolstov/cloudagent/command/guest_fsfreeze_status"
	_ "github.com/vtolstov/cloudagent/command/guest_fsfreeze_thaw"
	_ "github.com/vtolstov/cloudagent/command/guest_fsresize"
	_ "github.com/vtolstov/cloudagent/command/guest_fstrim"
	_ "github.com/vtolstov/cloudagent/command/guest_get_time"
	_ "github.com/vtolstov/cloudagent/command/guest_info"
	_ "github.com/vtolstov/cloudagent/command/guest_memory_info"
	_ "github.com/vtolstov/cloudagent/command/guest_ping"
	_ "github.com/vtolstov/cloudagent/command/guest_set_time"
	_ "github.com/vtolstov/cloudagent/command/guest_set_user_password"
	_ "github.com/vtolstov/cloudagent/command/guest_shutdown"
	_ "github.com/vtolstov/cloudagent/command/guest_stats"
	_ "github.com/vtolstov/cloudagent/command/guest_sync"
	_ "github.com/vtolstov/cloudagent/command/guest_sync_delimited"

)

